const VERSION = '0.0.0.0.2';
const grid = document.querySelector('.grid');
const numColumns = 5;
const numButtonsPerColumn = 150; // generate 50 buttons per column
const columnNames = ["GBA", "3DS", "NDS", "PSX", "others"];
const buttonNames = [
   [ 
"Animon",
"Bleach Advance",
"Castlevania Aria of Sorrow",
"Dbz Supersonic Warrior",
"Dragon Ball Z Team Training v9.2",
"Dragon Ball Z The Legacy of Goku 2",
"Emerald Redux",
"Elite Redux 2.5",
"Fire Red",
"NarutoCouncil",
"NarutoCouncil 2",
"Naruto Pkmn",
"One Piece Dragon Dream",
"RadicalRed 4.1",
"Street Fighter",
"Pokemon Emerald Imperium", 
"Naruto: Ninja Destiny 2",
"Dragon Ball Z - Supersonic Warriors 2 (EU)", 
    "Button 19", "Button 20", "Button 21", "Button 22", "Button 23", 
    "Button 24", "Button 25", "Button 26", "Button 27", "Button 28", 
    "Button 29", "Button 30", "Button 31", "Button 32", "Button 33", 
    "Button 34", "Button 35", "Button 36", "Button 37", "Button 38", 
    "Button 39", "Button 40", "Button 41", "Button 42", "Button 43", 
    "Button 44", "Button 45", "Button 46", "Button 47", "Button 48", 
    "Button 49", "Button 50", "Button 51", "Button 52", "Button 53", 
    "Button 54", "Button 55", "Button 56", "Button 57", "Button 58", 
    "Button 59", "Button 60", "Button 61", "Button 62", "Button 63", 
    "Button 64", "Button 65", "Button 66", "Button 67", "Button 68", 
    "Button 69", "Button 70", "Button 71", "Button 72", "Button 73", 
    "Button 74", "Button 75", "Button 76", "Button 77", "Button 78", 
    "Button 79", "Button 80", "Button 81", "Button 82", "Button 83", 
    "Button 84", "Button 85", "Button 86", "Button 87", "Button 88", 
    "Button 89", "Button 90", "Button 91", "Button 92", "Button 93", 
    "Button 94", "Button 95", "Button 96", "Button 97", "Button 98", 
    "Button 99", "Button 100", "Button 101", "Button 102", "Button 103", 
    "Button 104", "Button 105", "Button 106", "Button 107", "Button 108", 
    "Button 109", "Button 110", "Button 111", "Button 112", "Button 113", 
    "Button 114", "Button 115", "Button 116", "Button 117", "Button 118", 
    "Button 119", "Button 120", "Button 121", "Button 122", "Button 123", 
    "Button 124", "Button 125", "Button 126", "Button 127", "Button 128", 
    "Button 129", "Button 130", "Button 131", "Button 132", "Button 133", 
    "Button 134", "Button 135", "Button 136", "Button 137", "Button 138", 
    "Button 139", "Button 140", "Button 141", "Button 142", "Button 143", 
    "Button 144", "Button 145", "Button 146", "Button 147", "Button 148", 
    "Button 149", "Button 150"
    ],
    [
        "Button 1", "Button 2", "Button 3", "Button 4", "Button 5",
        "Button 6", "Button 7", "Button 8", "Button 9", "Button 10",
        "Button 11", "Button 12", "Button 13", "Button 14", "Button 15",
        "Button 16", "Button 17", "Button 18", "Button 19", "Button 20",
        "Button 21", "Button 22", "Button 23", "Button 24", "Button 25",
        "Button 26", "Button 27", "Button 28", "Button 29", "Button 30",
        "Button 31", "Button 32", "Button 33", "Button 34", "Button 35",
        "Button 36", "Button 37", "Button 38", "Button 39", "Button 40",
        "Button 41", "Button  42", "Button 43", "Button 44", "Button 45",
        "Button 46 ", "Button 47", "Button 48", "Button 49", "Button 50","Button 51", "Button 52", "Button 53", "Button 54", "Button 55", "Button 56", "Button 57", "Button 58", "Button 59", "Button 60", "Button 61", "Button 62", "Button 63", "Button 64", "Button 65", "Button 66", "Button 67", "Button 68", "Button 69", "Button 70", "Button 71", "Button 72", "Button 73", "Button 74", "Button 75", "Button 76", "Button 77", "Button 78", "Button 79", "Button 80", "Button 81", "Button 82", "Button 83", "Button 84", "Button 85", "Button 86", "Button 87", "Button 88", "Button 89", "Button 90", "Button 91", "Button 92", "Button 93", "Button 94", "Button 95", "Button 96", "Button 97", "Button 98", "Button 99", "Button 100", "Button 101", "Button 102", "Button 103", "Button 104", "Button 105", "Button 106", "Button 107", "Button 108", "Button 109", "Button 110", "Button 111", "Button 112", "Button 113", "Button 114", "Button 115", "Button 116", "Button 117", "Button 118", "Button 119", "Button 120", "Button 121", "Button 122", "Button 123", "Button 124", "Button 125", "Button 126", "Button 127", "Button 128", "Button 129", "Button 130", "Button 131", "Button 132", "Button 133", "Button 134", "Button 135", "Button 136", "Button 137", "Button 138", "Button 139", "Button 140", "Button 141", "Button 142", "Button 143", "Button 144", "Button 145", "Button 146", "Button 147", "Button 148", "Button 149", "Button 150"
    ],
    [
        "Button 1", "Button 2", "Button 3", "Button 4", "Button 5",
        "Button 6", "Button 7", "Button 8", "Button 9", "Button 10",
        "Button 11", "Button 12", "Button 13", "Button 14", "Button 15",
        "Button 16", "Button 17", "Button 18", "Button 19", "Button 20",
        "Button 21", "Button 22", "Button 23", "Button 24", "Button 25",
        "Button 26", "Button 27", "Button 28", "Button 29", "Button 30",
        "Button 31", "Button 32", "Button 33", "Button 34", "Button 35",
        "Button 36", "Button 37", "Button 38", "Button 39", "Button 40",
        "Button 41", "Button 42", "Button 43", "Button 44", "Button 45",
        "Button 46", "Button 47", "Button 48", "Button 49", "Button 50","Button 51", "Button 52", "Button 53", "Button 54", "Button 55", "Button 56", "Button 57", "Button 58", "Button 59", "Button 60", "Button 61", "Button 62", "Button 63", "Button 64", "Button 65", "Button 66", "Button 67", "Button 68", "Button 69", "Button 70", "Button 71", "Button 72", "Button 73", "Button 74", "Button 75", "Button 76", "Button 77", "Button 78", "Button 79", "Button 80", "Button 81", "Button 82", "Button 83", "Button 84", "Button 85", "Button 86", "Button 87", "Button 88", "Button 89", "Button 90", "Button 91", "Button 92", "Button 93", "Button 94", "Button 95", "Button 96", "Button 97", "Button 98", "Button 99", "Button 100", "Button 101", "Button 102", "Button 103", "Button 104", "Button 105", "Button 106", "Button 107", "Button 108", "Button 109", "Button 110", "Button 111", "Button 112", "Button 113", "Button 114", "Button 115", "Button 116", "Button 117", "Button 118", "Button 119", "Button 120", "Button 121", "Button 122", "Button 123", "Button 124", "Button 125", "Button 126", "Button 127", "Button 128", "Button 129", "Button 130", "Button 131", "Button 132", "Button 133", "Button 134", "Button 135", "Button 136", "Button 137", "Button 138", "Button 139", "Button 140", "Button 141", "Button 142", "Button 143", "Button 144", "Button 145", "Button 146", "Button 147", "Button 148", "Button 149", "Button 150"
    ],
    [
        "Button 1", "Button 2", "Button 3", "Button 4", "Button 5",
        "Button 6", "Button 7", "Button 8", "Button 9", "Button 10",
        "Button 11", "Button 12", "Button 13", "Button 14", "Button 15",
        "Button 16", "Button 17", "Button 18", "Button 19", "Button 20",
        "Button 21", "Button 22", "Button 23", "Button 24", "Button 25",
        "Button 26", "Button 27", "Button 28", "Button 29", "Button 30",
        "Button 31", "Button 32", "Button 33", "Button 34", "Button 35",
        "Button 36", "Button 37", "Button 38", "Button 39", "Button 40",
        "Button 41", "Button 42", "Button 43", "Button 44", "Button 45",
        "Button 46", "Button 47", "Button 48", "Button 49", "Button 50","Button 51", "Button 52", "Button 53", "Button 54", "Button 55", "Button 56", "Button 57", "Button 58", "Button 59", "Button 60", "Button 61", "Button 62", "Button 63", "Button 64", "Button 65", "Button 66", "Button 67", "Button 68", "Button 69", "Button 70", "Button 71", "Button 72", "Button 73", "Button 74", "Button 75", "Button 76", "Button 77", "Button 78", "Button 79", "Button 80", "Button 81", "Button 82", "Button 83", "Button 84", "Button 85", "Button 86", "Button 87", "Button 88", "Button 89", "Button 90", "Button 91", "Button 92", "Button 93", "Button 94", "Button 95", "Button 96", "Button 97", "Button 98", "Button 99", "Button 100", "Button 101", "Button 102", "Button 103", "Button 104", "Button 105", "Button 106", "Button 107", "Button 108", "Button 109", "Button 110", "Button 111", "Button 112", "Button 113", "Button 114", "Button 115", "Button 116", "Button 117", "Button 118", "Button 119", "Button 120", "Button 121", "Button 122", "Button 123", "Button 124", "Button 125", "Button 126", "Button 127", "Button 128", "Button 129", "Button 130", "Button 131", "Button 132", "Button 133", "Button 134", "Button 135", "Button 136", "Button 137", "Button 138", "Button 139", "Button 140", "Button 141", "Button 142", "Button 143", "Button 144", "Button 145", "Button 146", "Button 147", "Button 148", "Button 149", "Button 150"
    ],
    ["Bad Recovery", "Cryptshitty", "Button 3", "Button 4", "Button 5"
        
    ]
];
const buttonLinks = [
    [
    "https://dinkeres.github.io/emulator/Roms/Animon.html",
    "https://dinkeres.github.io/emulator/Roms/Bleach%20Advance.html",
    "https://dinkeres.github.io/emulator/Roms/Castlevania_Aria_of_Sorrow.html",
    "https://dinkeres.github.io/emulator/Roms/Dbz_Supersonic_warriors.html",
    "https://dinkeres.github.io/emulator/Roms/Dragon%20Ball%20Z%20Team%20Training%20v9.2.html",
    "https://dinkeres.github.io/emulator/Roms/Dragon%20Ball%20Z%20-%20The%20Legacy%20of%20Goku%20II%20(USA).html",
    "https://dinkeres.github.io/emulator/Roms/Eliteredux.html",
    "https://dinkeres.github.io/emulator/Roms/Elite%20Redux%202.5.html",
    "https://dinkeres.github.io/emulator/Roms/fire%20red.html",
    "https://dinkeres.github.io/emulator/Roms/Naruto%20Council.html",
    "https://dinkeres.github.io/emulator/Roms/NarutoCouncil%202.html",
    "https://dinkeres.github.io/emulator/Roms/Narutopkmn.html",
    "https://dinkeres.github.io/emulator/Roms/One%20Piece%20Dragon%20Dream.html",
    "https://dinkeres.github.io/emulator/Roms/radicalred%204.1.html",
    "https://dinkeres.github.io/emulator/Roms/Pokemon%20Emerald%20Imperium.html",
   "https://dinkeres.github.io/emulator/Roms/Naruto:%20Ninja%20Destiny%202%20.html",
   "https://dinkeres.github.io/emulator/Roms/Dragon%20Ball%20Z%20-%20Supersonic%20Warriors%202.html",
        "https://www.example.com/gba-button-19",
        "https://www.example.com/gba-button-20",
        "https://www.example.com/gba-button-21",
        "https://www.example.com/gba-button-22",
        "https://www.example.com/gba-button-23",
        "https://www.example.com/gba-button-24",
        "https://www.example.com/gba-button-25",
        "https://www.example.com/gba-button-26",
        "https://www.example.com/gba-button-27",
        "https://www.example.com/gba-button-28",
        "https://www.example.com/gba-button-29",
        "https://www.example.com/gba-button-30",
        "https://www.example.com/gba-button-31",
        "https://www.example.com/gba-button-32",
        "https://www.example.com/gba-button-33",
        "https://www.example.com/gba-button-34",
        "https://www.example.com/gba-button-35",
        "https://www.example.com/gba-button-36",
        "https://www.example.com/gba-button-37",
        "https://www.example.com/gba-button-38",
        "https://www.example.com/gba-button-39",
        "https://www.example.com/gba-button-40",
        "https://www.example.com/gba-button-41",
        "https://www.example.com/gba-button-42",
        "https://www.example.com/gba-button-43",
        "https://www.example.com/gba-button-44",
        "https://www.example.com/gba-button-45",
        "https://www.example.com/gba-button-46",
        "https://www.example.com/gba-button-47",
        "https://www.example.com/gba-button-48",
        "https://www.example.com/gba-button-49",
        "https://www.example.com/gba-button-50",
        "https://www.example.com/gba-button-51",
        "https://www.example.com/gba-button-52",
        "https://www.example.com/gba-button-53",
        "https://www.example.com/gba-button-54",
        "https://www.example.com/gba-button-55",
        "https://www.example.com/gba-button-56",
        "https://www.example.com/gba-button-57",
        "https://www.example.com/gba-button-58",
        "https://www.example.com/gba-button-59",
        "https://www.example.com/gba-button-60",
        "https://www.example.com/gba-button-61",
        "https://www.example.com/gba-button-62",
        "https://www.example.com/gba-button-63",
        "https://www.example.com/gba-button-64",
        "https://www.example.com/gba-button-65",
        "https://www.example.com/gba-button-66",
        "https://www.example.com/gba-button-67",
        "https://www.example.com/gba-button-68",
        "https://www.example.com/gba-button-69",
        "https://www.example.com/gba-button-70",
        "https://www.example.com/gba-button-71",
        "https://www.example.com/gba-button-72",
        "https://www.example.com/gba-button-73",
        "https://www.example.com/gba-button-74",
        "https://www.example.com/gba-button-75",
        "https://www.example.com/gba-button-76",
        "https://www.example.com/gba-button-77",
        "https://www.example.com/gba-button-78",
        "https://www.example.com/gba-button-79",
        "https://www.example.com/gba-button-80",
        "https://www.example.com/gba-button-81",
        "https://www.example.com/gba-button-82",
        "https://www.example.com/gba-button-83",
        "https://www.example.com/gba-button-84",
        "https://www.example.com/gba-button-85",
        "https://www.example.com/gba-button-86",
        "https://www.example.com/gba-button-87",
        "https://www.example.com/gba-button-88",
        "https://www.example.com/gba-button-89",
        "https://www.example.com/gba-button-90",
        "https://www.example.com/gba-button-91",
        "https://www.example.com/gba-button-92",
        "https://www.example.com/gba-button-93",
        "https://www.example.com/gba-button-94",
        "https://www.example.com/gba-button-95",
        "https://www.example.com/gba-button-96",
        "https://www.example.com/gba-button-97",
        "https://www.example.com/gba-button-98",
        "https://www.example.com/gba-button-99",
        "https://www.example.com/gba-button-100",
        "https://www.example.com/gba-button-101",
        "https://www.example.com/gba-button-102",
        "https://www.example.com/gba-button-103",
        "https://www.example.com/gba-button-104",
        "https://www.example.com/gba-button-105",
        "https://www.example.com/gba-button-106",
        "https://www.example.com/gba-button-107",
        "https://www.example.com/gba-button-108",
        "https://www.example.com/gba-button-109",
        "https://www.example.com/gba-button-110",
        "https://www.example.com/gba-button-111",
        "https://www.example.com/gba-button-112",
        "https://www.example.com/gba-button-113",
        "https://www.example.com/gba-button-114",
        "https://www.example.com/gba-button-115",
        "https://www.example.com/gba-button-116",
        "https://www.example.com/gba-button-117",
        "https://www.example.com/gba-button-118",
        "https://www.example.com/gba-button-119",
        "https://www.example.com/gba-button-120",
        "https://www.example.com/gba-button-121",
        "https://www.example.com/gba-button-122",
        "https://www.example.com/gba-button-123",
        "https://www.example.com/gba-button-124",
        "https://www.example.com/gba-button-125",
        "https://www.example.com/gba-button-126",
        "https://www.example.com/gba-button-127",
        "https://www.example.com/gba-button-128",
        "https://www.example.com/gba-button-129",
        "https://www.example.com/gba-button-130",
        "https://www.example.com/gba-button-131",
        "https://www.example.com/gba-button-132",
        "https://www.example.com/gba-button-133",
        "https://www.example.com/gba-button-134",
        "https://www.example.com/gba-button-135",
        "https://www.example.com/gba-button-136",
        "https://www.example.com/gba-button-137",
        "https://www.example.com/gba-button-138",
        "https://www.example.com/gba-button-139",
        "https://www.example.com/gba-button-140",
        "https://www.example.com/gba-button-141",
        "https://www.example.com/gba-button-142",
        "https://www.example.com/gba-button-143",
        "https://www.example.com/gba-button-144",
        "https://www.example.com/gba-button-145",
        "https://www.example.com/gba-button-146",
        "https://www.example.com/gba-button-147",
        "https://www.example.com/gba-button-148",
        "https://www.example.com/gba-button-149",
        "https://www.example.com/gba-button-150"
    ],
    [
        "https://www.example.com/3ds-button-1",
        "https://www.example.com/3ds-button-2",
        "https://www.example.com/3ds-button-3",
        "https://www.example.com/3ds-button-4",
        "https://www.example.com/3ds-button-5",
        "https://www.example.com/3ds-button-6",
        "https://www.example.com/3ds-button-7",
        "https://www.example.com/3ds-button-8",
        "https://www.example.com/3ds-button-9",
        "https://www.example.com/3ds-button-10",
        "https://www.example.com/3ds-button-11",
        "https://www.example.com/3ds-button-12",
        "https://www.example.com/3ds-button-13",
        "https://www.example.com/3ds-button-14",
        "https://www.example.com/3ds-button-15",
        "https://www.example.com/3ds-button-16",
        "https://www.example.com/3ds-button-17",
        "https://www.example.com/3ds-button-18",
        "https://www.example.com/3ds-button-19",
        "https://www.example.com/3ds-button-20",
        "https://www.example.com/3ds-button-21",
        "https://www.example.com/3ds-button-22",
        "https://www.example.com/3ds-button-23",
        "https://www.example.com/3ds-button-24",
        "https://www.example.com/3ds-button-25",
        "https://www.example.com/3ds-button-26",
        "https://www.example.com/3ds-button-27",
        "https://www.example.com/3ds-button-28",
        "https://www.example.com/3ds-button-29",
        "https://www.example.com/3ds-button-30",
        "https://www.example.com/3ds-button-31",
        "https://www.example.com/3ds-button-32",
        "https://www.example.com/3ds-button-33",
        "https://www.example.com/3ds-button-34",
        "https://www.example.com/3ds-button-35",
        "https://www.example.com/3ds-button-36",
        "https://www.example.com/3ds-button-37",
        "https://www.example.com/3ds-button-38",
        "https://www.example.com/3ds-button-39",
        "https://www.example.com/3ds-button-40",
        "https://www.example.com/3ds-button-41",
        "https://www.example.com/3ds-button-42",
        "https://www.example.com/3ds-button-43",
        "https://www.example.com/3ds-button-44",
        "https://www.example.com/3ds-button-45",
        "https://www.example.com/3ds-button-46",
        "https://www.example.com/3ds-button-47",
        "https://www.example.com/3ds-button-48",
        "https://www.example.com/3ds-button-49",
        "https://www.example.com/3ds-button-50",
        "https://www.example.com/3ds-button-51",
        "https://www.example.com/3ds-button-52",
        "https://www.example.com/3ds-button-53",
        "https://www.example.com/3ds-button-54",
        "https://www.example.com/3ds-button-55",
        "https://www.example.com/3ds-button-56",
        "https://www.example.com/3ds-button-57",
        "https://www.example.com/3ds-button-58",
        "https://www.example.com/3ds-button-59",
        "https://www.example.com/3ds-button-60",
        "https://www.example.com/3ds-button-61",
        "https://www.example.com/3ds-button-62",
        "https://www.example.com/3ds-button-63",
        "https://www.example.com/3ds-button-64",
        "https://www.example.com/3ds-button-65",
        "https://www.example.com/3ds-button-66",
        "https://www.example.com/3ds-button-67",
        "https://www.example.com/3ds-button-68",
        "https://www.example.com/3ds-button-69",
        "https://www.example.com/3ds-button-70",
        "https://www.example.com/3ds-button-71",
        "https://www.example.com/3ds-button-72",
        "https://www.example.com/3ds-button-73",
        "https://www.example.com/3ds-button-74",
        "https://www.example.com/3ds-button-75",
        "https://www.example.com/3ds-button-76",
        "https://www.example.com/3ds-button-77",
        "https://www.example.com/3ds-button-78",
        "https://www.example.com/3ds-button-79",
        "https://www.example.com/3ds-button-80",
        "https://www.example.com/3ds-button-81",
        "https://www.example.com/3ds-button-82",
        "https://www.example.com/3ds-button-83",
        "https://www.example.com/3ds-button-84",
        "https://www.example.com/3ds-button-85",
        "https://www.example.com/3ds-button-86",
        "https://www.example.com/3ds-button-87",
        "https://www.example.com/3ds-button-88",
        "https://www.example.com/3ds-button-89",
        "https://www.example.com/3ds-button-90",
        "https://www.example.com/3ds-button-91",
        "https://www.example.com/3ds-button-92",
        "https://www.example.com/3ds-button-93",
        "https://www.example.com/3ds-button-94",
        "https://www.example.com/3ds-button-95",
        "https://www.example.com/3ds-button-96",
        "https://www.example.com/3ds-button-97",
        "https://www.example.com/3ds-button-98",
        "https://www.example.com/3ds-button-99",
        "https://www.example.com/3ds-button-100",
        "https://www.example.com/3ds-button-101",
        "https://www.example.com/3ds-button-102",
        "https://www.example.com/3ds-button-103",
        "https://www.example.com/3ds-button-104",
        "https://www.example.com/3ds-button-105",
        "https://www.example.com/3ds-button-106",
        "https://www.example.com/3ds-button-107",
        "https://www.example.com/3ds-button-108",
        "https://www.example.com/3ds-button-109",
        "https://www.example.com/3ds-button-110",
        "https://www.example.com/3ds-button-111",
        "https://www.example.com/3ds-button-112",
        "https://www.example.com/3ds-button-113",
        "https://www.example.com/3ds-button-114",
        "https://www.example.com/3ds-button-115",
        "https://www.example.com/3ds-button-116",
        "https://www.example.com/3ds-button-117",
        "https://www.example.com/3ds-button-118",
        "https://www.example.com/3ds-button-119",
        "https://www.example.com/3ds-button-120",
        "https://www.example.com/3ds-button-121",
        "https://www.example.com/3ds-button-122",
        "https://www.example.com/3ds-button-123",
        "https://www.example.com/3ds-button-124",
        "https://www.example.com/3ds-button-125",
        "https://www.example.com/3ds-button-126",
        "https://www.example.com/3ds-button-127",
        "https://www.example.com/3ds-button-128",
        "https://www.example.com/3ds-button-129",
        "https://www.example.com/3ds-button-130",
        "https://www.example.com/3ds-button-131",
        "https://www.example.com/3ds-button-132",
        "https://www.example.com/3ds-button-133",
        "https://www.example.com/3ds-button-134",
        "https://www.example.com/3ds-button-135",
        "https://www.example.com/3ds-button-136",
        "https://www.example.com/3ds-button-137",
        "https://www.example.com/3ds-button-138",
        "https://www.example.com/3ds-button-139",
        "https://www.example.com/3ds-button-140",
        "https://www.example.com/3ds-button-141",
        "https://www.example.com/3ds-button-142",
        "https://www.example.com/3ds-button-143",
        "https://www.example.com/3ds-button-144",
        "https://www.example.com/3ds-button-145",
        "https://www.example.com/3ds-button-146",
        "https://www.example.com/3ds-button-147",
        "https://www.example.com/3ds-button-148",
        "https://www.example.com/3ds-button-149",
        "https://www.example.com/3ds-button-150"
    ],    
    [
        "https://www.example.com/nds-button-1",
        "https://www.example.com/nds-button-2",
        "https://www.example.com/nds-button-3",
        "https://www.example.com/nds-button-4",
        "https://www.example.com/nds-button-5",
        "https://www.example.com/nds-button-6",
        "https://www.example.com/nds-button-7",
        "https://www.example.com/nds-button-8",
        "https://www.example.com/nds-button-9",
        "https://www.example.com/nds-button-10",
        "https://www.example.com/nds-button-11",
        "https://www.example.com/nds-button-12",
        "https://www.example.com/nds-button-13",
        "https://www.example.com/nds-button-14",
        "https://www.example.com/nds-button-15",
        "https://www.example.com/nds-button-16",
        "https://www.example.com/nds-button-17",
        "https://www.example.com/nds-button-18",
        "https://www.example.com/nds-button-19",
        "https://www.example.com/nds-button-20",
        "https://www.example.com/nds-button-21",
        "https://www.example.com/nds-button-22",
        "https://www.example.com/nds-button-23",
        "https://www.example.com/nds-button-24",
        "https://www.example.com/nds-button-25",
        "https://www.example.com/nds-button-26",
        "https://www.example.com/nds-button-27",
        "https://www.example.com/nds-button-28",
        "https://www.example.com/nds-button-29",
        "https://www.example.com/nds-button-30",
        "https://www.example.com/nds-button-31",
        "https://www.example.com/nds-button-32",
        "https://www.example.com/nds-button-33",
        "https://www.example.com/nds-button-34",
        "https://www.example.com/nds-button-35",
        "https://www.example.com/nds-button-36",
        "https://www.example.com/nds-button-37",
        "https://www.example.com/nds-button-38",
        "https://www.example.com/nds-button-39",
        "https://www.example.com/nds-button-40",
        "https://www.example.com/nds-button-41",
        "https://www.example.com/nds-button-42",
        "https://www.example.com/nds-button-43",
        "https://www.example.com/nds-button-44",
        "https://www.example.com/nds-button-45",
        "https://www.example.com/nds-button-46",
        "https://www.example.com/nds-button-47",
        "https://www.example.com/nds-button-48",
        "https://www.example.com/nds-button-49",
        "https://www.example.com/nds-button-50",
        "https://www.example.com/nds-button-51",
        "https://www.example.com/nds-button-52",
        "https://www.example.com/nds-button-53",
        "https://www.example.com/nds-button-54",
        "https://www.example.com/nds-button-55",
        "https://www.example.com/nds-button-56",
        "https://www.example.com/nds-button-57",
        "https://www.example.com/nds-button-58",
        "https://www.example.com/nds-button-59",
        "https://www.example.com/nds-button-60",
        "https://www.example.com/nds-button-61",
        "https://www.example.com/nds-button-62",
        "https://www.example.com/nds-button-63",
        "https://www.example.com/nds-button-64",
        "https://www.example.com/nds-button-65",
        "https://www.example.com/nds-button-66",
        "https://www.example.com/nds-button-67",
        "https://www.example.com/nds-button-68",
        "https://www.example.com/nds-button-69",
        "https://www.example.com/nds-button-70",
        "https://www.example.com/nds-button-71",
        "https://www.example.com/nds-button-72",
        "https://www.example.com/nds-button-73",
        "https://www.example.com/nds-button-74",
        "https://www.example.com/nds-button-75",
        "https://www.example.com/nds-button-76",
        "https://www.example.com/nds-button-77",
        "https://www.example.com/nds-button-78",
        "https://www.example.com/nds-button-79",
        "https://www.example.com/nds-button-80",
        "https://www.example.com/nds-button-81",
        "https://www.example.com/nds-button-82",
        "https://www.example.com/nds-button-83",
        "https://www.example.com/nds-button-84",
        "https://www.example.com/nds-button-85",
        "https://www.example.com/nds-button-86",
        "https://www.example.com/nds-button-87",
        "https://www.example.com/nds-button-88",
        "https://www.example.com/nds-button-89",
        "https://www.example.com/nds-button-90",
        "https://www.example.com/nds-button-91",
        "https://www.example.com/nds-button-92",
        "https://www.example.com/nds-button-93",
        "https://www.example.com/nds-button-94",
        "https://www.example.com/nds-button-95",
        "https://www.example.com/nds-button-96",
        "https://www.example.com/nds-button-97",
        "https://www.example.com/nds-button-98",
        "https://www.example.com/nds-button-99",
        "https://www.example.com/nds-button-100",
        "https://www.example.com/nds-button-101",
        "https://www.example.com/nds-button-102",
        "https://www.example.com/nds-button-103",
        "https://www.example.com/nds-button-104",
        "https://www.example.com/nds-button-105",
        "https://www.example.com/nds-button-106",
        "https://www.example.com/nds-button-107",
        "https://www.example.com/nds-button-108",
        "https://www.example.com/nds-button-109",
        "https://www.example.com/nds-button-110",
        "https://www.example.com/nds-button-111",
        "https://www.example.com/nds-button-112",
        "https://www.example.com/nds-button-113",
        "https://www.example.com/nds-button-114",
        "https://www.example.com/nds-button-115",
        "https://www.example.com/nds-button-116",
        "https://www.example.com/nds-button-117",
        "https://www.example.com/nds-button-118",
        "https://www.example.com/nds-button-119",
        "https://www.example.com/nds-button-120",
        "https://www.example.com/nds-button-121",
        "https://www.example.com/nds-button-122",
        "https://www.example.com/nds-button-123",
        "https://www.example.com/nds-button-124",
        "https://www.example.com/nds-button-125",
        "https://www.example.com/nds-button-126",
        "https://www.example.com/nds-button-127",
        "https://www.example.com/nds-button-128",
        "https://www.example.com/nds-button-129",
        "https://www.example.com/nds-button-130",
        "https://www.example.com/nds-button-131",
        "https://www.example.com/nds-button-132",
        "https://www.example.com/nds-button-133",
        "https://www.example.com/nds-button-134",
        "https://www.example.com/nds-button-135",
        "https://www.example.com/nds-button-136",
        "https://www.example.com/nds-button-137",
        "https://www.example.com/nds-button-138",
        "https://www.example.com/nds-button-139",
        "https://www.example.com/nds-button-140",
        "https://www.example.com/nds-button-141",
        "https://www.example.com/nds-button-142",
        "https://www.example.com/nds-button-143",
        "https://www.example.com/nds-button-144",
        "https://www.example.com/nds-button-145",
        "https://www.example.com/nds-button-146",
        "https://www.example.com/nds-button-147",
        "https://www.example.com/nds-button-148",
        "https://www.example.com/nds-button-149",
        "https://www.example.com/nds-button-150"
    ],   
     [
        "https://www.example.com/psx-button-1",
        "https://www.example.com/psx-button-2",
        "https://www.example.com/psx-button-3",
        "https://www.example.com/psx-button-4",
        "https://www.example.com/psx-button-5",
        "https://www.example.com/psx-button-6",
        "https://www.example.com/psx-button-7",
        "https://www.example.com/psx-button-8",
        "https://www.example.com/psx-button-9",
        "https://www.example.com/psx-button-10",
        "https://www.example.com/psx-button-11",
        "https://www.example.com/psx-button-12",
        "https://www.example.com/psx-button-13",
        "https://www.example.com/psx-button-14",
        "https://www.example.com/psx-button-15",
        "https://www.example.com/psx-button-16",
        "https://www.example.com/psx-button-17",
        "https://www.example.com/psx-button-18",
        "https://www.example.com/psx-button-19",
        "https://www.example.com/psx-button-20",
        "https://www.example.com/psx-button-21",
        "https://www.example.com/psx-button-22",
        "https://www.example.com/psx-button-23",
        "https://www.example.com/psx-button-24",
        "https://www.example.com/psx-button-25",
        "https://www.example.com/psx-button-26",
        "https://www.example.com/psx-button-27",
        "https://www.example.com/psx-button-28",
        "https://www.example.com/psx-button-29",
        "https://www.example.com/psx-button-30",
        "https://www.example.com/psx-button-31",
        "https://www.example.com/psx-button-32",
        "https://www.example.com/psx-button-33",
        "https://www.example.com/psx-button-34",
        "https://www.example.com/psx-button-35",
        "https://www.example.com/psx-button-36",
        "https://www.example.com/psx-button-37",
        "https://www.example.com/psx-button-38",
        "https://www.example.com/psx-button-39",
        "https://www.example.com/psx-button-40",
        "https://www.example.com/psx-button-41",
        "https://www.example.com/psx-button-42",
        "https://www.example.com/psx-button-43",
        "https://www.example.com/psx-button-44",
        "https://www.example.com/psx-button-45",
        "https://www.example.com/psx-button-46",
        "https://www.example.com/psx-button-47",
        "https://www.example.com/psx-button-48",
        "https://www.example.com/psx-button-49",
        "https://www.example.com/psx-button-50",
        "https://www.example.com/psx-button-51",
        "https://www.example.com/psx-button-52",
        "https://www.example.com/psx-button-53",
        "https://www.example.com/psx-button-54",
        "https://www.example.com/psx-button-55",
        "https://www.example.com/psx-button-56",
        "https://www.example.com/psx-button-57",
        "https://www.example.com/psx-button-58",
        "https://www.example.com/psx-button-59",
        "https://www.example.com/psx-button-60",
        "https://www.example.com/psx-button-61",
        "https://www.example.com/psx-button-62",
        "https://www.example.com/psx-button-63",
        "https://www.example.com/psx-button-64",
        "https://www.example.com/psx-button-65",
        "https://www.example.com/psx-button-66",
        "https://www.example.com/psx-button-67",
        "https://www.example.com/psx-button-68",
        "https://www.example.com/psx-button-69",
        "https://www.example.com/psx-button-70",
        "https://www.example.com/psx-button-71",
        "https://www.example.com/psx-button-72",
        "https://www.example.com/psx-button-73",
        "https://www.example.com/psx-button-74",
        "https://www.example.com/psx-button-75",
        "https://www.example.com/psx-button-76",
        "https://www.example.com/psx-button-77",
        "https://www.example.com/psx-button-78",
        "https://www.example.com/psx-button-79",
        "https://www.example.com/psx-button-80",
        "https://www.example.com/psx-button-81",
        "https://www.example.com/psx-button-82",
        "https://www.example.com/psx-button-83",
        "https://www.example.com/psx-button-84",
        "https://www.example.com/psx-button-85",
        "https://www.example.com/psx-button-86",
        "https://www.example.com/psx-button-87",
        "https://www.example.com/psx-button-88",
        "https://www.example.com/psx-button-89",
        "https://www.example.com/psx-button-90",
        "https://www.example.com/psx-button-91",
        "https://www.example.com/psx-button-92",
        "https://www.example.com/psx-button-93",
        "https://www.example.com/psx-button-94",
        "https://www.example.com/psx-button-95",
        "https://www.example.com/psx-button-96",
        "https://www.example.com/psx-button-97",
        "https://www.example.com/psx-button-98",
        "https://www.example.com/psx-button-99",
        "https://www.example.com/psx-button-100",
        "https://www.example.com/psx-button-101",
        "https://www.example.com/psx-button-102",
        "https://www.example.com/psx-button-103",
        "https://www.example.com/psx-button-104",
        "https://www.example.com/psx-button-105",
        "https://www.example.com/psx-button-106",
        "https://www.example.com/psx-button-107",
        "https://www.example.com/psx-button-108",
        "https://www.example.com/psx-button-109",
        "https://www.example.com/psx-button-110",
        "https://www.example.com/psx-button-111",
        "https://www.example.com/psx-button-112",
        "https://www.example.com/psx-button-113",
        "https://www.example.com/psx-button-114",
        "https://www.example.com/psx-button-115",
        "https://www.example.com/psx-button-116",
        "https://www.example.com/psx-button-117",
        "https://www.example.com/psx-button-118",
        "https://www.example.com/psx-button-119",
        "https://www.example.com/psx-button-120",
        "https://www.example.com/psx-button-121",
        "https://www.example.com/psx-button-122",
        "https://www.example.com/psx-button-123",
        "https://www.example.com/psx-button-124",
        "https://www.example.com/psx-button-125",
        "https://www.example.com/psx-button-126",
        "https://www.example.com/psx-button-127",
        "https://www.example.com/psx-button-128",
        "https://www.example.com/psx-button-129",
        "https://www.example.com/psx-button-130",
        "https://www.example.com/psx-button-131",
        "https://www.example.com/psx-button-132",
        "https://www.example.com/psx-button-133",
        "https://www.example.com/psx-button-134",
        "https://www.example.com/psx-button-135",
        "https://www.example.com/psx-button-136",
        "https://www.example.com/psx-button-137",
        "https://www.example.com/psx-button-138",
        "https://www.example.com/psx-button-139",
        "https://www.example.com/psx-button-140",
        "https://www.example.com/psx-button-141",
        "https://www.example.com/psx-button-142",
        "https://www.example.com/psx-button-143",
        "https://www.example.com/psx-button-144",
        "https://www.example.com/psx-button-145",
        "https://www.example.com/psx-button-146",
        "https://www.example.com/psx-button-147",
        "https://www.example.com/psx-button-148",
        "https://www.example.com/psx-button-149",
        "https://www.example.com/psx-button-150"
    ],
    [
        "https://dinkeres.github.io/emulator/UnblockMethods/BadRecovery.html",
        "https://dinkeres.github.io/emulator/UnblockMethods/cryptoshitty.html"
    ]    
    
];
for (let i = 0; i < numColumns; i++) {
    const column = document.createElement('div');
    column.className = 'column';
    
    const columnTitle = document.createElement('div');
    columnTitle.className = 'column-title';
    columnTitle.textContent = columnNames[i]; // use the column name from the array
    column.appendChild(columnTitle);
    
    for (let j = 0; j < numButtonsPerColumn; j++) {
        const button = document.createElement('button');
        button.textContent = buttonNames[i][j]; // use the custom button name from the 2D array
        button.className = 'button'; // Add the button class for styling
        
        button.onclick = function() {
            let url = buttonLinks[i][j];
            const iframeContainer = document.getElementById('iframe-container');
            const iframe = document.getElementById('iframe');
            iframe.src = url;
            iframeContainer.style.display = 'block';
        };
        column.appendChild(button);
    }
    
    grid.appendChild(column);
}
