name: Update Script Tag

on:
  push:
    branches:
      - main

jobs:
  update-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update script tag
        run: |
          TIMESTAMP=$(date +%s)
          sed -i "s|https://cdn.jsdelivr.net/gh/Dinkeres/emulator@main/.github/workflows/Script.js|https://cdn.jsdelivr.net/gh/Dinkeres/emulator@main/.github/workflows/Script.js?${TIMESTAMP}|g" index.html
      - name: Commit changes
        run: |
          git add .
          git commit -m "Update script tag with new timestamp"
          git push origin main
