name: Update Script on jsDelivr

on:
  push:
    branches:
      - main

jobs:
  update-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update script tag with new timestamp
        run: |
          TIMESTAMP=$(date +%s)
          sed -i "s/<script src=\"https:\/\/cdn.jsdelivr.net\/gh\/Dinkeres\/emulator@main\/script.js\"><\/script>/<script src=\"https:\/\/cdn.jsdelivr.net\/gh\/Dinkeres\/emulator@${TIMESTAMP}\/script.js\"><\/script>/" index.html

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update script tag with new timestamp"
          git config --global credential.helper store
          echo "https://${SECRET_PAT}:@github.com" >> ~/.git-credentials
          git push https://github.com/Dinkeres/emulator.git main
