name: Update Script on jsDelivr

on:
  push:
    branches:
      - main

jobs:
  update-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change permissions on Script.js
        run: chmod 755 .github/workflows/Script.js

      - name: Update Script on jsDelivr
        env:
          JSDELIVR_URL: https://cdn.jsdelivr.net/gh/Dinkeres/emulator@main/.github/workflows/Script.js
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: |
          curl -X PUT \
          $JSDELIVR_URL \
          -H 'Authorization: Bearer $SECRET_TOKEN' \
          -H 'Content-Type: application/javascript' \
          -T .github/workflows/Script.js

      - name: Update script tag
        run: |
          TIMESTAMP=$(date +%s)
          sed -i "s|https://cdn.jsdelivr.net/gh/Dinkeres/emulator@main/.github/workflows/Script.js|https://cdn.jsdelivr.net/gh/Dinkeres/emulator@main/.github/workflows/Script.js?${TIMESTAMP}|g" index.html

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update script tag with new timestamp"
          git push origin main
