name: Update jsDelivr

on:
  push:
    branches:
      - main

jobs:
  update-jsdelivr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update jsDelivr
        env:
          JSDELIVR_URL: https://cdn.jsdelivr.net/gh/Dinkeres/emulator@main/Script.js
        run: |
          curl -X PUT \
          $JSDELIVR_URL \
          -H 'Authorization: Bearer ${{ secrets.SECRET_TOKEN }}' \
          -H 'Content-Type: application/javascript' \
          -T script.js
